apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    env: dev
    tier: db
spec:
  replica: 1
  selector:
    matchLabels:
      app: mongodb
      env: dev
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        env: dev
        tier: db
    spec:
      containers:
      - name: mongodb
        image: satyology/mongodb1
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
  namespace: roboshop
  labels:
    app: mongodb
    env: dev
    tier: db
spec:
  selector:
    app: mongodb
    env: dev
    tier: db
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
