apiVersion: v1
kind: Deplyment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    env: dev
    tier: db
spec:
  replica: 1
  selector:
    matchLabels:
      app: catalogue
      env: dev
      tier: db
  template:
    metadata:
      labels:
        app: catalogue
        env: dev
        tier: db
    spec:
      containers:
      - name: catalogue
        image: satyology/catalogue1
---
apiVersion: v1
kind: Service
metadata:
  name: cataloguesvc
  namespace: roboshop
  labels:
    app: catalogue
    env: dev
    tier: db
spec:
  selector:
    app: catalogue
    env: dev
    tier: db
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
