apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    env: dev
    tier: app
data:
---
apiVersion: v1
kind: Deplyment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    env: dev
    tier: app
spec:
  replica: 1
  selector:
    matchLabels:
      app: catalogue
      env: dev
      tier: app
  template:
    metadata:
      labels:
        app: catalogue
        env: dev
        tier: app
    spec:
      containers:
      - name: catalogue
        image: satyology/catalogue1
---
apiVersion: v1
kind: Service
metadata:
  name: cataloguesvc
  namespace: roboshop
  labels:
    app: catalogue
    env: dev
    tier: app
spec:
  selector:
    app: catalogue
    env: dev
    tier: app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
