apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    env: dev
    tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodbsvc:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    env: dev
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      env: dev
      tier: app
  template:
    metadata:
      labels:
        app: catalogue
        env: dev
        tier: app
    spec:
      containers:
      - name: catalogue
        image: satyology/catalogue1
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: cataloguesvc
  namespace: roboshop
  labels:
    app: catalogue
    env: dev
    tier: app
spec:
  selector:
    app: catalogue
    env: dev
    tier: app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
